// SoBrowserActionBHO.idl : IDL source for SoBrowserActionBHO
//

// This file will be processed by the MIDL tool to
// produce the type library (SoBrowserActionBHO.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(72C52942-80E4-4704-A053-635AC0428115),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICSoBABHO : IDispatch{
};
[
	uuid(BCC617EF-FD08-4EE7-89C7-DA25D925487B),
	version(1.0),
]
library SoBrowserActionBHOLib
{
	importlib("stdole2.tlb");
	[
		uuid(C1A74118-CCA4-4E9D-928D-88385ECD2382)		
	]
	coclass CSoBABHO
	{
		[default] interface ICSoBABHO;
	};
};

